monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - security

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine", "!console"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: debug
                channels: ["security"]
            mailer:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.mailer.log"
                level: debug # ou 'info' pour moins de détails
                channels: ["mailer"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            mailer:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.mailer.log"
                level: debug # ou 'info' pour moins de détails
                channels: ["mailer"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            mailer:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.mailer.log"
                level: debug # ou 'info' pour moins de détails
                channels: ["mailer"]
            
