vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        images_users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
